"""
Clinical Reasoning Pipeline — multi-agent visit assessment.

Orchestrates the full 5-step clinical reasoning flow:
  1. MedASR: audio → transcript (skip if text provided)
  2. Load patient context: EHR profile + vitals + medications + recent visits
  3. GPAgent: transcript + EHR → GPAssessment + board routing
  4. Orchestrator: route to specialist agents
  5. SynthesisAgent: all inputs → final VisitSynthesis

Returns ClinicalVisitResult — a flat dataclass ready for JSON serialisation
and form field mapping in the UI.

Layer: pipelines (consumes agents, models, data)
"""
from __future__ import annotations

import logging
from dataclasses import dataclass, asdict, field
from pathlib import Path
from typing import Optional

logger = logging.getLogger(__name__)

DISCLAIMER = (
    "This clinical assessment was generated by AI using a multi-agent reasoning pipeline. "
    "It is intended for clinical decision support only. All findings require clinician review "
    "and professional judgement before any clinical action is taken. This is not a substitute "
    "for clinical examination."
)


@dataclass
class ClinicalVisitResult:
    """
    Final structured output of the clinical reasoning pipeline.

    Maps directly to the New Visit form fields in the UI.
    All fields are editable by the clinician before saving to DB.
    requires_review is always True — never remove this.
    """

    transcript: str
    reason_for_visit: str
    soap: dict               # {subjective, objective, assessment, plan}
    diagnoses: list          # [{code, display, code_system, status}]
    recommended_orders: list # [{category, test_display, test_code, test_code_system, urgency, rationale}]
    agents_invoked: list
    cot_log: list            # [{agent, reasoning}]
    key_findings: str = ""
    requires_review: bool = True
    disclaimer: str = DISCLAIMER


def run_clinical_reasoning(
    patient_id: str,
    audio_path: Optional[Path] = None,
    transcript: Optional[str] = None,
    image=None,
) -> ClinicalVisitResult:
    """
    Run the full multi-agent clinical reasoning pipeline for a visit.

    Args:
        patient_id:  Patient ID string (e.g. "P001").
        audio_path:  Path to WAV/WebM audio file. Provide audio_path OR transcript.
        transcript:  Pre-existing text transcript. Provide audio_path OR transcript.
        image:       Optional PIL.Image.Image (de-identified) for image-capable agents.

    Returns:
        ClinicalVisitResult with all form fields populated.

    Raises:
        ValueError: If neither audio_path nor transcript is provided.
    """
    if audio_path is None and not transcript:
        raise ValueError("Provide either audio_path or transcript")

    from src.config.loader import load_config
    config = load_config()

    # ── Step 1: Audio → Transcript ─────────────────────────────────────────────
    if transcript:
        logger.info(
            "Clinical pipeline: using provided transcript (%d chars)", len(transcript)
        )
    else:
        logger.info("Clinical pipeline: transcribing audio from %s", audio_path)
        from src.models.medasr.inference import transcribe_medical_audio
        asr_result = transcribe_medical_audio(str(audio_path))
        transcript = asr_result["transcript"]
        logger.info("Transcript generated (%d chars)", len(transcript))

    # ── Step 2: Load patient context ───────────────────────────────────────────
    from src.data.db import (
        get_patient_profile,
        get_patient_vitals,
        get_patient_medications,
        get_patient_visits,
    )

    profile = get_patient_profile(patient_id) or {}
    vitals = get_patient_vitals(patient_id) if profile else {}
    medications = get_patient_medications(patient_id) if profile else []
    visits = get_patient_visits(patient_id) if profile else []

    ehr_summary = _format_ehr_summary(profile, vitals, medications, visits)
    ehr_summary_dict = _profile_to_dict(profile, vitals, medications) if profile else {}

    # ── Step 3: GP Agent (with full patient history) ───────────────────────────
    logger.info("Clinical pipeline: running GPAgent (pass 2 — with EHR history)")
    from src.agents.gp_agent import GPAgent

    gp_assessment = GPAgent(config).run(
        transcript=transcript,
        ehr_summary=ehr_summary_dict,
    )

    board_routing = gp_assessment.get("board_routing", {})
    cot_log: list[dict] = [
        {
            "agent": "GPAgent",
            "reasoning": gp_assessment.get("chain_of_thought", ""),
        }
    ]

    # ── Step 4: Specialist agents via orchestrator ─────────────────────────────
    logger.info("Clinical pipeline: running specialist agents via orchestrator")
    from src.agents.orchestrator import run_specialists

    # Combine EHR medications + medications mentioned in the transcript by GP
    drug_names: list[str] = []
    seen_drugs: set[str] = set()
    for m in medications:
        inn = (m.get("inn") or m.get("medicine_name") or "").strip()
        if inn and inn not in seen_drugs:
            drug_names.append(inn)
            seen_drugs.add(inn)
    for d in gp_assessment.get("medications_mentioned", []):
        if d and d not in seen_drugs:
            drug_names.append(d)
            seen_drugs.add(d)

    patient_symptoms = _extract_symptoms(gp_assessment)

    specialist_reports = run_specialists(
        board_routing=board_routing,
        transcript=transcript,
        ehr_summary=ehr_summary,
        drug_names=drug_names,
        patient_symptoms=patient_symptoms,
        config=config,
        image=image,
    )

    # Collect specialist CoT entries
    for agent_name, report in specialist_reports.items():
        reasoning = (
            report.get("chain_of_thought")
            or report.get("reasoning")
            or report.get("_error", "No reasoning captured")
        )
        cot_log.append(
            {"agent": f"{agent_name.capitalize()}Agent", "reasoning": str(reasoning)}
        )

    # ── Step 5: Synthesis Agent ────────────────────────────────────────────────
    logger.info("Clinical pipeline: running SynthesisAgent")
    from src.agents.synthesis_agent import SynthesisAgent

    synthesis = SynthesisAgent(config).run(
        transcript=transcript,
        ehr_summary=ehr_summary,
        gp_assessment=gp_assessment,
        specialist_reports=specialist_reports,
    )

    # Append synthesis agent's own CoT entry (appended inside SynthesisAgent.run)
    for entry in synthesis.get("cot_log", []):
        if entry.get("agent") == "SynthesisAgent":
            cot_log.append(entry)

    # ── Step 6: Assemble ClinicalVisitResult ──────────────────────────────────
    agents_invoked = synthesis.get("agents_invoked") or (
        ["GPAgent"]
        + [f"{k.capitalize()}Agent" for k in specialist_reports.keys()]
        + ["SynthesisAgent"]
    )

    # Normalise diagnoses: synthesis uses {code, display, code_system, status}
    diagnoses = [
        {
            "code": d.get("code", ""),
            "display": d.get("display", ""),
            "code_system": d.get("code_system", "ICD-10"),
            "status": d.get("status", "provisional"),
        }
        for d in synthesis.get("diagnoses", [])
    ]

    # Fallback: if synthesis produced no diagnoses, use GP icd_codes
    if not diagnoses:
        diagnoses = [
            {
                "code": ic.get("code", ""),
                "display": ic.get("description", ic.get("display", "")),
                "code_system": "ICD-10",
                "status": "provisional",
            }
            for ic in gp_assessment.get("icd_codes", [])
        ]

    soap_raw = synthesis.get("soap") or gp_assessment.get("soap") or {}
    soap = soap_raw if isinstance(soap_raw, dict) else {}

    return ClinicalVisitResult(
        transcript=transcript,
        reason_for_visit=(
            synthesis.get("reason_for_visit")
            or gp_assessment.get("chief_complaint", "")
        ),
        soap=soap,
        diagnoses=diagnoses,
        recommended_orders=synthesis.get("recommended_orders", []),
        agents_invoked=agents_invoked,
        cot_log=cot_log,
        key_findings=synthesis.get("key_findings", ""),
    )


# ── Helpers ────────────────────────────────────────────────────────────────────

def _format_ehr_summary(
    profile: dict,
    vitals: dict,
    medications: list,
    visits: list,
) -> str:
    """Format patient EHR data into a compact clinical context string."""
    lines: list[str] = []

    # Demographics
    name = f"{profile.get('given_names', '')} {profile.get('family_name', '')}".strip()
    age = profile.get("age", "?")
    sex = profile.get("sex_at_birth", "?")
    blood_type = profile.get("blood_type") or "unknown"
    if name:
        lines.append(
            f"Patient: {name}, Age {age}, Sex: {sex}, Blood type: {blood_type}"
        )

    # Active conditions
    active_conds = [c for c in profile.get("conditions", []) if c.get("status") == "active"]
    if active_conds:
        cond_str = "; ".join(
            f"{c.get('display', '')} ({c.get('code', '')})"
            for c in active_conds[:6]
        )
        lines.append(f"Active conditions: {cond_str}")

    # Allergies
    allergies = profile.get("allergies", [])
    if allergies:
        allergy_str = "; ".join(
            f"{a.get('substance', '')} ({a.get('severity', '?')})"
            for a in allergies[:5]
        )
        lines.append(f"Allergies: {allergy_str}")

    # Current medications
    if medications:
        med_names: list[str] = []
        seen: set[str] = set()
        for m in medications:
            inn = (m.get("inn") or m.get("medicine_name") or "").strip()
            if inn and inn not in seen:
                med_names.append(inn)
                seen.add(inn)
            if len(med_names) >= 10:
                break
        lines.append(f"Current medications ({len(med_names)}): {', '.join(med_names)}")

    # Last 3 visits
    recent_visits = visits[:3]
    if recent_visits:
        visit_strs = [
            f"{v.get('visit_date', '?')} — "
            f"{v.get('patient_reported_reason', 'no reason recorded')}"
            for v in recent_visits
        ]
        lines.append(f"Last {len(recent_visits)} visits: {'; '.join(visit_strs)}")

    # Latest vitals
    vital_parts: list[str] = []
    if vitals.get("weight_history"):
        w = vitals["weight_history"][0]
        vital_parts.append(f"Weight: {w.get('weight_kg')}kg")
    if vitals.get("bp_history"):
        bp = vitals["bp_history"][0]
        vital_parts.append(
            f"BP: {bp.get('systolic_mmhg')}/{bp.get('diastolic_mmhg')}mmHg"
        )
    if vitals.get("hr_history"):
        hr = vitals["hr_history"][0]
        vital_parts.append(f"HR: {hr.get('heart_rate_bpm')}bpm")
    if vitals.get("spo2_history"):
        spo2 = vitals["spo2_history"][0]
        vital_parts.append(f"SpO2: {spo2.get('spo2_pct')}%")
    if vital_parts:
        lines.append(f"Latest vitals: {', '.join(vital_parts)}")

    return "\n".join(lines)


def _profile_to_dict(profile: dict, vitals: dict, medications: list) -> dict:
    """Convert profile/vitals/medications into the nested dict GPAgent expects as ehr_summary."""
    return {
        "demographics": {
            "name": (
                f"{profile.get('given_names', '')} {profile.get('family_name', '')}"
            ).strip(),
            "age": profile.get("age"),
            "sex": profile.get("sex_at_birth"),
            "blood_type": profile.get("blood_type"),
        },
        "active_conditions": [
            {
                "code": c.get("code"),
                "display": c.get("display"),
                "onset": c.get("onset_date"),
            }
            for c in profile.get("conditions", [])
            if c.get("status") == "active"
        ],
        "allergies": [
            {"substance": a.get("substance"), "severity": a.get("severity")}
            for a in profile.get("allergies", [])
        ],
        "current_medications": [
            {
                "name": m.get("medicine_name"),
                "inn": m.get("inn"),
                "dose": m.get("dose"),
                "frequency": m.get("frequency"),
            }
            for m in medications[:10]
        ],
        "latest_vitals": {
            "weight_kg": (
                vitals["weight_history"][0].get("weight_kg")
                if vitals.get("weight_history")
                else None
            ),
            "systolic_mmhg": (
                vitals["bp_history"][0].get("systolic_mmhg")
                if vitals.get("bp_history")
                else None
            ),
            "diastolic_mmhg": (
                vitals["bp_history"][0].get("diastolic_mmhg")
                if vitals.get("bp_history")
                else None
            ),
            "heart_rate_bpm": (
                vitals["hr_history"][0].get("heart_rate_bpm")
                if vitals.get("hr_history")
                else None
            ),
            "spo2_pct": (
                vitals["spo2_history"][0].get("spo2_pct")
                if vitals.get("spo2_history")
                else None
            ),
        },
    }


def _extract_symptoms(gp_assessment: dict) -> list[str]:
    """Extract a simple symptom list from the GP assessment."""
    symptoms: list[str] = []
    chief = gp_assessment.get("chief_complaint", "")
    if chief:
        symptoms.append(chief)
    for diff in gp_assessment.get("differentials", [])[:3]:
        reasoning = diff.get("reasoning", "")
        if reasoning:
            symptoms.append(reasoning[:100])
    return symptoms
