"""
Drug interaction check pipeline.

Full end-to-end pipeline:
  medication list (brand or generic names)
  → INN resolution via RxNorm
  → DDI check via RxNav (batch, all pairs)
  → PubMed RAG evidence retrieval (optional, MedGemma-powered)
  → Side-effect aggregation via openFDA
  → Symptom-side-effect matching (if patient symptoms provided)
  → Formatted PharmacologyAssessment dict

Owner agent: pharmacology-agent
Config: configs/agents/pharmacology.yaml
"""
from __future__ import annotations

import logging
from typing import List, Optional

logger = logging.getLogger(__name__)

DISCLAIMER = (
    "This drug interaction check was generated by AI using publicly available "
    "databases (NIH RxNav/RxNorm, openFDA, PubMed). It is not a substitute for "
    "clinical pharmacist review. Always consult a qualified healthcare professional "
    "before making medication changes."
)


def run_drug_check_pipeline(
    drug_names: List[str],
    patient_symptoms: Optional[List[str]] = None,
    enable_pubmed_rag: bool = True,
    enable_side_effects: bool = True,
    ncbi_api_key: Optional[str] = None,
    pubmed_retmax: int = 6,
) -> dict:
    """
    Full DDI + side-effect + symptom-matching pipeline.

    Args:
        drug_names:          List of drug names (trade or generic, as prescribed).
        patient_symptoms:    Patient-reported symptoms from transcript (optional).
                             Used for symptom-medication correlation.
        enable_pubmed_rag:   If True, search PubMed for interaction evidence.
        enable_side_effects: If True, retrieve side effects from openFDA.
        ncbi_api_key:        Optional NCBI API key for higher PubMed rate limits.
        pubmed_retmax:       Max PubMed results per drug pair.

    Returns:
        Dict conforming to PharmacologyAssessment structure with requires_review=True.
    """
    from src.pharmacology.rxnav_client import RxNavClient
    from src.pharmacology.normalization import medicine_to_inns, inns_to_ingredient_rxcuis
    from src.pharmacology.interactions import check_all_interactions_among_ingredients

    if not drug_names:
        return {
            "medications_checked": [],
            "resolved_inns": [],
            "interactions": [],
            "critical_count": 0,
            "major_count": 0,
            "moderate_count": 0,
            "overall_risk_level": "none_found",
            "rag_interactions": [],
            "side_effects_aggregated": [],
            "symptom_matches": [],
            "recommendations": [],
            "requires_review": True,
            "disclaimer": DISCLAIMER,
        }

    client = RxNavClient()

    # ── 1. Resolve drug names to INNs ─────────────────────────────────────────
    logger.info("DDI pipeline: resolving %d drugs to INNs", len(drug_names))
    resolved_inns: List[str] = []
    resolution_map: dict = {}  # original_name → [inns]

    for med in drug_names:
        inns = medicine_to_inns(client, med)
        if inns:
            resolution_map[med] = inns
            resolved_inns.extend(inns)
        else:
            logger.warning("DDI pipeline: could not resolve %r to INN — using as-is", med)
            resolution_map[med] = [med.strip()]
            resolved_inns.append(med.strip())

    # Deduplicate INNs
    seen: set = set()
    unique_inns: List[str] = []
    for inn in resolved_inns:
        key = inn.lower()
        if key not in seen:
            seen.add(key)
            unique_inns.append(inn)

    # ── 2. RxNav DDI check (batch, all pairs) ─────────────────────────────────
    logger.info("DDI pipeline: checking interactions for %d INNs", len(unique_inns))
    rxnav_interactions = []
    if len(unique_inns) >= 2:
        rxnav_interactions = check_all_interactions_among_ingredients(unique_inns)
    logger.info("DDI pipeline: found %d RxNav interactions", len(rxnav_interactions))

    # ── 3. PubMed RAG (optional) ───────────────────────────────────────────────
    rag_interactions = []
    if enable_pubmed_rag and len(unique_inns) >= 2:
        rag_interactions = _run_pubmed_rag(
            unique_inns,
            ncbi_api_key=ncbi_api_key,
            retmax=pubmed_retmax,
        )

    # ── 4. Side effects via openFDA (optional) ────────────────────────────────
    side_effects_aggregated = []
    if enable_side_effects and unique_inns:
        from src.pharmacology.side_effects_openfda import aggregate_side_effects
        side_effects_aggregated = aggregate_side_effects(unique_inns)
        logger.info(
            "DDI pipeline: retrieved %d aggregated side effects",
            len(side_effects_aggregated),
        )

    # ── 5. Symptom matching (if symptoms provided) ────────────────────────────
    symptom_matches = []
    if patient_symptoms and side_effects_aggregated:
        from src.pharmacology.symptom_matcher import match_symptoms_to_effects
        symptom_matches = match_symptoms_to_effects(patient_symptoms, side_effects_aggregated)

    # ── 6. Build structured report ────────────────────────────────────────────
    interactions_list = _format_rxnav_interactions(rxnav_interactions)
    critical_count = sum(1 for i in interactions_list if i.get("severity") == "critical")
    major_count = sum(1 for i in interactions_list if i.get("severity") == "major")
    moderate_count = sum(1 for i in interactions_list if i.get("severity") in ("moderate", "med"))

    overall_risk = _compute_overall_risk(critical_count, major_count, moderate_count)
    recommendations = _build_recommendations(interactions_list, symptom_matches, overall_risk)

    return {
        "medications_checked": drug_names,
        "resolved_inns": unique_inns,
        "resolution_map": resolution_map,
        "interactions": interactions_list,
        "critical_count": critical_count,
        "major_count": major_count,
        "moderate_count": moderate_count,
        "overall_risk_level": overall_risk,
        "rag_interactions": rag_interactions,
        "side_effects_aggregated": [
            {
                "effect": se["effect"],
                "contributors": se["contributors"],
                "combined_probability": se.get("combined_probability"),
                "max_severity": se.get("max_severity"),
            }
            for se in side_effects_aggregated[:20]  # top 20 to keep response manageable
        ],
        "symptom_matches": symptom_matches,
        "recommendations": recommendations,
        "requires_review": True,
        "disclaimer": DISCLAIMER,
    }


def _run_pubmed_rag(
    inns: List[str],
    ncbi_api_key: Optional[str],
    retmax: int,
) -> list:
    """Run PubMed RAG for all unique INN pairs."""
    from src.pharmacology.pubmed_rag import (
        build_pubmed_query,
        pubmed_search_pmids,
        pubmed_fetch_summaries,
        medgemma_extract_claims,
    )

    results = []
    for i in range(len(inns)):
        for j in range(i + 1, len(inns)):
            inn_a, inn_b = inns[i], inns[j]
            try:
                query = build_pubmed_query(inn_a, inn_b)
                pmids = pubmed_search_pmids(query, retmax=retmax, api_key=ncbi_api_key)
                summaries = pubmed_fetch_summaries(pmids, api_key=ncbi_api_key)
                claims = medgemma_extract_claims(inn_a, inn_b, summaries)
                results.extend(claims)
            except Exception as exc:
                logger.warning("PubMed RAG failed for (%s, %s): %s", inn_a, inn_b, exc)

    logger.info("DDI pipeline: retrieved %d RAG interaction claims", len(results))
    return results


def _severity_bucket_to_label(bucket: str) -> str:
    """Map internal severity bucket to standardised label."""
    mapping = {
        "critical": "critical",
        "high": "major",
        "major": "major",
        "med": "moderate",
        "moderate": "moderate",
        "low": "minor",
        "minor": "minor",
    }
    return mapping.get(bucket.lower(), "moderate")


def _format_rxnav_interactions(rxnav_interactions: list) -> list:
    """Format RxNav interaction results for the API response."""
    formatted = []
    for ix in rxnav_interactions:
        # Support both dataclass (.ingredient_1_inn) and dict ("ingredient_1_inn") access
        if hasattr(ix, "ingredient_1_inn"):
            drug_a = ix.ingredient_1_inn
            drug_b = ix.ingredient_2_inn
            description = ix.interaction
            severity = _severity_bucket_to_label(ix.severity or "moderate")
        else:
            drug_a = ix.get("ingredient_1_inn", "")
            drug_b = ix.get("ingredient_2_inn", "")
            description = ix.get("interaction", ix.get("description", ""))
            severity = _severity_bucket_to_label(ix.get("severity", "moderate") or "moderate")

        formatted.append({
            "drug_a": drug_a,
            "drug_b": drug_b,
            "severity": severity,
            "description": description,
            "source": "RxNav",
            "management": _default_management(severity),
        })

    # Sort: critical first, then major, moderate, minor
    severity_order = {"critical": 0, "major": 1, "moderate": 2, "minor": 3}
    return sorted(formatted, key=lambda x: severity_order.get(x["severity"], 99))


def _default_management(severity: str) -> str:
    """Default management guidance by severity."""
    return {
        "critical": "Avoid combination — contraindicated. Consult pharmacist/prescriber immediately.",
        "major": "Use with extreme caution. Monitor closely or consider alternatives.",
        "moderate": "Monitor patient and review if symptoms worsen. Clinical judgement required.",
        "minor": "Minimally significant. Note and monitor; usually no change needed.",
    }.get(severity, "Clinical review recommended.")


def _compute_overall_risk(critical: int, major: int, moderate: int) -> str:
    if critical > 0:
        return "critical"
    if major > 0:
        return "high"
    if moderate > 0:
        return "moderate"
    return "low"


def _build_recommendations(
    interactions: list,
    symptom_matches: list,
    overall_risk: str,
) -> List[str]:
    """Build top-level clinical recommendations."""
    recs: List[str] = []

    critical = [i for i in interactions if i.get("severity") == "critical"]
    major = [i for i in interactions if i.get("severity") == "major"]

    for ix in critical:
        recs.append(
            f"CRITICAL: {ix['drug_a']} + {ix['drug_b']} — {ix['description'][:120]}. "
            "Do not co-prescribe without specialist guidance."
        )

    for ix in major:
        recs.append(
            f"MAJOR: {ix['drug_a']} + {ix['drug_b']} — {ix['description'][:120]}. "
            "Monitor closely or consider alternative."
        )

    if symptom_matches:
        high_conf = [m for m in symptom_matches if m.get("similarity", 0) >= 0.9]
        for match in high_conf[:3]:
            recs.append(
                f"Symptom alert: '{match['symptom']}' may be a side effect of "
                f"{', '.join(match['contributors'][:2])} ({match['matched_effect']}). "
                "Review with clinician."
            )

    if overall_risk in ("critical", "high"):
        recs.append(
            "Urgent pharmacist review recommended given high-severity interaction(s)."
        )

    if not recs:
        recs.append("No significant drug interactions identified. Continue routine monitoring.")

    return recs
