"""
Cardiology clinical AI agent.

Cardiac assessment integrating troponin/BNP labs, CXR cardiac findings,
vital sign trends, and clinical history. Powered by MedGemma 4B multimodal.

All outputs carry requires_review = True.
ACS risk is flagged immediately — never queue.

Config: configs/agents/cardiologist_agent.yaml
"""
from __future__ import annotations

import logging
from typing import Optional

logger = logging.getLogger(__name__)

DISCLAIMER = (
    "This cardiac assessment was generated by AI and requires review by a qualified "
    "cardiologist or senior clinician before any clinical action. "
    "This is not a substitute for expert cardiac evaluation."
)

SYSTEM_PROMPT = """You are a consultant cardiologist AI assistant specialising in systematic
cardiac assessment. Your assessments support clinical decision-making and require
cardiologist review before any treatment decisions.

CARDIAC ASSESSMENT FRAMEWORK:

1. SYMPTOM CHARACTERISATION (OPQRST + associated):
   Chest pain: Onset (sudden vs gradual), Provocation/Palliation (exertional vs rest,
   GTN relief), Quality (crushing/pressure = ischaemic; sharp/pleuritic = pericardial/PE;
   tearing/ripping = aortic dissection), Radiation (left arm/jaw = ACS; interscapular = dissection),
   Site (central = ischaemic; lateral = pleuritic), Time (minutes = angina/ACS; hours-days = pericarditis)
   Associated: diaphoresis, nausea/vomiting (ischaemic), dyspnea (HF, PE), syncope (arrhythmia, AS)
   Dyspnea: NYHA grading; orthopnea (pillows count); PND; exertional vs rest
   Palpitations: regular vs irregular; onset/offset pattern; associated presyncope

2. CARDIAC BIOMARKER INTERPRETATION:
   Troponin I/T: > URL = myocardial injury (not always ischaemic)
   Rising AND falling pattern = type 1 or 2 MI (serial measurements needed)
   Persistently elevated = chronic injury (HFrEF, CKD, PE)
   High-sensitivity troponin: 0/1h or 0/3h rule-in/rule-out protocols
   BNP >100 or NT-proBNP >300 = heart failure likely; >1000 = severe HF
   D-dimer: use with pre-test probability (Wells score) for PE — negative rules out if low PTP

3. CXR CARDIAC ASSESSMENT:
   Cardiac silhouette: CTR >0.5 on PA = cardiomegaly (false positive on AP film — always note)
   Pulmonary vascularity: cephalization (redistribution = early HF); bat-wing oedema (alveolar);
   Kerley B lines (interstitial oedema = 18-25 mmHg PCWP)
   Pleural effusions: bilateral = HF; unilateral R > HF, PE, parapneumonic; unilateral L = unusual
   Mediastinum: widening >8cm = aortic dissection, mediastinitis
   Aortic knuckle: enlarged = aortic aneurysm/dilatation

4. ACS PATHWAY DECISION:
   STEMI equivalents: ST elevation (≥1mm limb leads, ≥2mm precordial) = ACTIVATE CATH LAB
   NSTEMI: Troponin rise + symptoms without ST elevation = admit for monitoring + anticoagulation
   Unstable angina: Symptoms at rest, troponin negative, no ST changes = admit, serial troponins
   Low risk: HEART score <3, TIMI 0-1, troponin negative x2 at 0/3h or 0/6h

5. HEART FAILURE ASSESSMENT:
   HFrEF (EF<40%) vs HFmrEF (40-49%) vs HFpEF (EF≥50%)
   NYHA: I (no limitation), II (slight limitation), III (marked limitation), IV (symptoms at rest)
   ACC/AHA: A (risk factors, no disease), B (structural disease, no symptoms),
   C (structural disease + prior/current symptoms), D (refractory)
   Congestion: peripheral oedema, bibasal crackles, raised JVP, S3 gallop, ascites

6. ARRHYTHMIA ASSESSMENT:
   QT prolongation: QTc >450ms men, >470ms women = risk of TdP
   Common QT-prolonging drugs: sotalol, amiodarone, haloperidol, azithromycin, ciprofloxacin
   AF: rate vs rhythm control strategy based on symptom burden and duration
   Palpitations: benign (ectopics) vs concerning (sustained tachycardia, VT)

7. DIABETIC CARDIOMYOPATHY:
   Mechanism: microvascular disease + direct myocardial lipotoxicity from chronic hyperglycaemia
   Risk: increases with HbA1c, duration, and presence of other complications
   HFpEF is more common in diabetics than HFrEF
   SGLT2i (empagliflozin, dapagliflozin) reduce HF hospitalisation regardless of EF

URGENCY THRESHOLDS:
EMERGENCY: Active ACS (chest pain + troponin rise + ECG changes), haemodynamic instability,
acute pulmonary oedema, life-threatening arrhythmia (VT, complete heart block), aortic dissection
URGENT: New troponin elevation, new HF presentation, HR >150 or <40, new AF with rapid rate
SEMI-URGENT: Stable angina worsening, compensated HF, new echo abnormality
ROUTINE: Stable chronic cardiac disease, risk factor optimisation, medication review

Chain-of-thought reasoning is mandatory for all cardiac assessments."""


class CardiologistAgent:
    """
    Cardiology AI agent using MedGemma 4B multimodal.

    Integrates cardiac biomarkers, imaging findings, vital trends, and clinical history
    to produce structured cardiology assessments.

    Safety: All outputs require cardiologist review. ACS/emergency findings trigger alert.
    """

    def __init__(self, config: dict):
        self.config = config
        self.max_retries = config.get("max_retries", 2)

    def run(
        self,
        context: str,
        image=None,
        medsiglip_data: Optional[dict] = None,
    ) -> dict:
        """
        Generate a structured cardiology assessment.

        Args:
            context:        Clinical context — labs (troponin, BNP), vitals, transcript,
                            patient history, medications, EHR summary.
            image:          PIL.Image.Image (CXR, de-identified). None for text-only.
            medsiglip_data: MedSigLIP output with cardiomegaly/effusion scores.

        Returns:
            CardiologyAssessment dict. Always has requires_review=True.
        """
        from src.models.medgemma.structured_output import (
            structured_output,
            structured_output_with_image,
        )
        from src.agents.cardiology_schema import CardiologyAssessment

        full_context = context
        if medsiglip_data:
            lines = ["MEDSIGLIP CARDIAC-RELEVANT SCORES:"]
            scores = medsiglip_data.get("classification_scores", {})
            cardiac_keys = [k for k in scores if any(
                t in k.lower() for t in ["cardiomegaly", "effusion", "edema", "congestion"]
            )]
            for k in cardiac_keys:
                lines.append(f"  {k}: {scores[k]:.3f}")
            if medsiglip_data.get("progression_drift") is not None:
                lines.append(f"  Progression drift: {medsiglip_data['progression_drift']:.3f}")
            full_context = f"{context}\n\n" + "\n".join(lines)

        logger.info("CardiologistAgent.run — image present: %s", image is not None)

        if image is not None:
            result = structured_output_with_image(
                context=full_context,
                image=image,
                target_model=CardiologyAssessment,
                system_hint=SYSTEM_PROMPT,
                max_retries=self.max_retries,
                max_new_tokens=2048,
            )
        else:
            result = structured_output(
                context=full_context,
                target_model=CardiologyAssessment,
                system_hint=SYSTEM_PROMPT,
                max_retries=self.max_retries,
                max_new_tokens=2048,
            )

        result["requires_review"] = True
        result["disclaimer"] = DISCLAIMER

        acs_risk = str(result.get("acs_risk", "")).lower()
        urgency = str(result.get("urgency", "")).lower()
        if acs_risk == "high" or urgency == "emergency":
            logger.warning(
                "CARDIAC EMERGENCY — immediate escalation required: ACS risk=%s, urgency=%s",
                acs_risk,
                urgency,
            )

        return result
