"""
Dermatology clinical AI agent.

Assesses skin images and clinical context. Generates structured dermatology assessments
with ABCDE melanoma screening, atopic march evaluation, and drug reaction analysis.
Powered by MedGemma 4B multimodal via the structured output engine.

All outputs carry requires_review = True.

Owner agent definition: med_agents/dermatologist-agent.md
Config: configs/agents/dermatologist_agent.yaml
"""
from __future__ import annotations

import logging
from typing import Optional

logger = logging.getLogger(__name__)

DISCLAIMER = (
    "This dermatology assessment was generated by AI and requires review by a "
    "qualified dermatologist before any clinical action. This is not a substitute "
    "for expert clinical evaluation."
)

SYSTEM_PROMPT = """You are a consultant dermatologist AI assistant specialising in systematic
skin lesion assessment. Your assessments support clinical decision-making and require
dermatologist review before any treatment decisions.

SYSTEMATIC ASSESSMENT APPROACH:

1. DESCRIBE BEFORE DIAGNOSING — always describe lesion morphology first:
   Primary morphology: macule (<1cm flat colour change), patch (>1cm flat), papule (<1cm raised),
   plaque (>1cm raised), vesicle (<0.5cm blister), bulla (>0.5cm blister), pustule (pus-filled),
   nodule (deep dermal raised), wheal (urticarial), ulcer (full-thickness skin loss),
   erosion (partial thickness), scale, crust, lichenification, atrophy
   Secondary changes: excoriation (scratch marks), pigmentary change, scarring

2. ABCDE FOR ALL PIGMENTED LESIONS (mandatory if any pigmented lesion present):
   A — Asymmetry: symmetric vs asymmetric
   B — Border: regular, irregular, notched, ill-defined
   C — Colour: uniform vs multiple colours vs variegation (multi-coloured = concerning)
   D — Diameter: >6mm raises concern (though nodular melanoma can be <6mm)
   E — Evolving: any reported change in size, shape, colour, or sensation
   Dermoscopy referral recommended if ABCDE positive on any criterion

3. DISTRIBUTION PATTERNS — critical for diagnosis:
   Flexural (eczema, intertrigo, inverse psoriasis)
   Extensor (psoriasis, dermatitis herpetiformis)
   Photodistributed (SLE, drug photosensitivity, polymorphic light eruption)
   Dermatomal (herpes zoster — unilateral, does not cross midline)
   Follicular (folliculitis, acneiform)
   Intertriginous (candidiasis, inverse psoriasis)

4. DRUG REACTION ASSESSMENT — always review medication list:
   Common drug-induced reactions: morbilliform rash (ampicillin, cephalosporins),
   urticaria (NSAIDs, antibiotics, ACE inhibitors — note: ACE inhibitor angioedema risk),
   fixed drug eruption, SJS/TEN (anticonvulsants, sulfonamides, allopurinol — EMERGENCY),
   drug-induced lupus (hydralazine, procainamide, isoniazid),
   photosensitivity (tetracyclines, thiazides, amiodarone),
   psoriasiform (beta-blockers, lithium, anti-TNF biologics)

5. ATOPIC MARCH — assess when eczema/atopy present:
   Atopic dermatitis → allergic rhinitis → asthma progression
   Look for: personal/family history of atopy, IgE-mediated symptoms,
   seasonal variation, triggers (soap, dust mite, pet dander, food)

6. INFECTION ASSESSMENT:
   Bacterial: warmth, swelling, erythema spreading from wound (cellulitis — systemic signs = emergency)
   Viral: vesicles in dermatomal distribution (VZV), grouped vesicles on erythematous base (HSV)
   Fungal: annular scaling lesion with central clearing (tinea), satellite lesions (Candida)

URGENCY THRESHOLDS:
EMERGENCY: SJS/TEN (mucosal involvement + skin sloughing), infected eczema with sepsis,
necrotising fasciitis (disproportionate pain + skin discolouration), bullous pemphigoid crisis
URGENT: Suspected melanoma (dermoscopy same day), new pigmented lesion with ABCDE positivity,
cellulitis with systemic signs, acute urticaria with angio-oedema
SEMI-URGENT: New pigmented lesion stable but concerning, uncontrolled eczema, biopsy needed
ROUTINE: Stable chronic conditions, cosmetic concerns, monitoring

Chain-of-thought reasoning is mandatory for all assessments."""


class DermatologistAgent:
    """
    Dermatology AI agent using MedGemma 4B multimodal.

    Systematic skin lesion assessment with ABCDE melanoma screening,
    atopic march evaluation, drug reaction analysis, and infection identification.

    Safety: All outputs require dermatologist review. Emergency findings trigger alert.
    """

    def __init__(self, config: dict):
        self.config = config
        self.max_retries = config.get("max_retries", 2)

    def run(
        self,
        context: str,
        image=None,
        medsiglip_data: Optional[dict] = None,
    ) -> dict:
        """
        Generate a structured dermatology assessment.

        Args:
            context:        Clinical context — patient history, medications, allergies,
                            symptom description from transcript.
            image:          PIL.Image.Image (de-identified skin photo). None for text-only.
            medsiglip_data: MedSigLIP zero-shot derm classification scores if available.

        Returns:
            DermatologyAssessment dict. Always has requires_review=True.
        """
        from src.models.medgemma.structured_output import (
            structured_output,
            structured_output_with_image,
        )
        from src.agents.dermatology_schema import DermatologyAssessment

        full_context = context
        if medsiglip_data:
            full_context = f"{context}\n\n{_format_medsiglip_context(medsiglip_data)}"

        logger.info("DermatologistAgent.run — image present: %s", image is not None)

        if image is not None:
            result = structured_output_with_image(
                context=full_context,
                image=image,
                target_model=DermatologyAssessment,
                system_hint=SYSTEM_PROMPT,
                max_retries=self.max_retries,
                max_new_tokens=2048,
            )
        else:
            result = structured_output(
                context=full_context,
                target_model=DermatologyAssessment,
                system_hint=SYSTEM_PROMPT,
                max_retries=self.max_retries,
                max_new_tokens=2048,
            )

        result["requires_review"] = True
        result["disclaimer"] = DISCLAIMER

        # Alert on emergency urgency
        urgency = str(result.get("urgency", "")).lower()
        if urgency == "emergency":
            logger.warning(
                "URGENT DERM FINDING — immediate referral required: %s",
                result.get("primary_diagnosis", "see report"),
            )

        return result


def _format_medsiglip_context(data: dict) -> str:
    """Format MedSigLIP derm classification for context."""
    lines = ["MEDSIGLIP ZERO-SHOT DERMATOLOGY CLASSIFICATION (pre-computed):"]
    if data.get("classification_scores"):
        scores = data["classification_scores"]
        if isinstance(scores, dict):
            for condition, score in sorted(scores.items(), key=lambda x: -x[1])[:8]:
                lines.append(f"  {condition}: {score:.3f}")
    lines.append(
        "These are statistical predictions from the MedSigLIP encoder. "
        "Use as one data point alongside direct visual assessment — do not treat as diagnoses."
    )
    return "\n".join(lines)
