"""
General Practitioner / Attending clinical AI agent.

The AI primary care physician. First to see every case.
- Performs initial clinical reasoning with chain-of-thought
- Builds preliminary SOAP structure
- Extracts medication list for DDI check
- Decides which specialist agents to consult (board routing)
- Produces a GPAssessment via the structured output engine

All outputs carry requires_review = True.
Emergency urgency triggers immediate alert — never queue.

Owner agent definition: med_agents/gp-agent.md
Config: configs/agents/gp_agent.yaml
"""
from __future__ import annotations

import json
import logging
from typing import Optional

logger = logging.getLogger(__name__)

DISCLAIMER = (
    "This assessment was generated by AI and is intended for clinical decision "
    "support only. It is not a substitute for clinical examination and professional "
    "medical judgement. Always verify with a qualified clinician."
)

SYSTEM_PROMPT = """You are the AI attending physician — the primary care doctor who sees every case first.
Your role is to perform systematic clinical reasoning and orchestrate the specialist consultation board.

CLINICAL APPROACH:
1. Read the complete health profile: transcript, EHR history, medications, labs, vitals, imaging context
2. Perform systematic clinical assessment:
   - What is the chief complaint and how long has it been present?
   - What are the relevant risk factors (age, sex, family history, chronic conditions)?
   - What do the objective findings (vitals, labs, imaging signals) show?
   - What is the most likely diagnosis and what are plausible alternatives?
   - How urgent is this presentation?
3. Convene the specialist board: based on ALL available evidence, decide which specialists to consult.
   This is NOT reflexive — each routing decision must be justified by specific evidence.

CLINICAL RULES:
- Chain-of-thought reasoning is MANDATORY — document your clinical logic step by step
- Never provide specific drug dosages
- Always use standard medical terminology
- List differentials from most to least likely with supporting reasoning for each
- Classify urgency explicitly and explain why: Emergency / Urgent / Routine
- Emergency = life-threatening or time-sensitive (activate immediately, do not queue)
- Urgent = needs same-day or next-day assessment
- Routine = can be addressed at next scheduled visit
- If information is insufficient to reason safely, document the gap in documentation_gaps
- Never fabricate clinical findings not present in the provided context
- Never make a single definitive diagnosis without acknowledging uncertainty

BOARD ROUTING — ALWAYS ACTIVE:
- Pharmacology agent: run DDI check + symptom-medication correlation on EVERY visit with ≥2 medications

BOARD ROUTING — EVIDENCE-BASED:
Route to radiologist if: imaging is present OR radiology report needed
Route to cardiologist if: chest pain / palpitations / troponin elevated / BNP elevated / cardiomegaly
Route to dermatologist if: skin image present OR eczema/rash/lesion mentioned
Route to pulmonologist if: wheeze / COPD / effusion on CXR / respiratory symptoms
Route to endocrinologist if: HbA1c >6.5% / diabetes management / TSH abnormal / fundus image"""


def build_gp_context(
    transcript: str,
    ehr_summary: Optional[dict] = None,
    medsiglip_summary: Optional[str] = None,
    imaging_present: bool = False,
    imaging_modalities: Optional[list] = None,
) -> str:
    """
    Build the full clinical context string for the GP assessment.

    Args:
        transcript:         Clinical transcript from MedASR or text input.
        ehr_summary:        EHR data dict (demographics, conditions, meds, labs, vitals).
        medsiglip_summary:  Pre-formatted MedSigLIP analysis string (optional).
        imaging_present:    Whether any imaging is available this visit.
        imaging_modalities: List of imaging types present (e.g., ["CXR", "fundus"]).

    Returns:
        Formatted context string for the structured output engine.
    """
    parts: list[str] = []

    parts.append(f"CLINICAL TRANSCRIPT:\n{transcript}")

    if ehr_summary:
        parts.append(f"PATIENT EHR SUMMARY:\n{json.dumps(ehr_summary, indent=2)}")

    if imaging_present:
        modalities = ", ".join(imaging_modalities or ["unspecified"])
        parts.append(f"IMAGING AVAILABLE THIS VISIT: {modalities}")

    if medsiglip_summary:
        parts.append(f"MEDSIGLIP IMAGE ANALYSIS:\n{medsiglip_summary}")

    return "\n\n".join(parts)


class GPAgent:
    """
    GP/Attending clinical AI agent using MedGemma via the structured output engine.

    Produces a full GPAssessment with chain-of-thought, SOAP note, urgency,
    differential diagnoses, and board routing decisions.

    Safety: All outputs require clinician review. Emergency triggers immediate alert.
    """

    def __init__(self, config: dict):
        self.config = config
        self.max_retries = config.get("max_retries", 2)

    def run(
        self,
        transcript: str,
        ehr_summary: Optional[dict] = None,
        medsiglip_summary: Optional[str] = None,
        imaging_present: bool = False,
        imaging_modalities: Optional[list] = None,
    ) -> dict:
        """
        Run the GP assessment.

        Args:
            transcript:         Clinical transcript (from MedASR or text input).
                                Must be de-identified before calling.
            ehr_summary:        Patient EHR data (demographics, conditions, meds, labs).
            medsiglip_summary:  Pre-computed MedSigLIP analysis string.
            imaging_present:    Whether imaging is available this visit.
            imaging_modalities: Types of imaging present (["CXR"], ["derm"], etc.).

        Returns:
            GPAssessment dict with requires_review=True.
        """
        from src.models.medgemma.structured_output import structured_output
        from src.agents.gp_schema import GPAssessment
        from src.utils.audit import log_inference

        context = build_gp_context(
            transcript=transcript,
            ehr_summary=ehr_summary,
            medsiglip_summary=medsiglip_summary,
            imaging_present=imaging_present,
            imaging_modalities=imaging_modalities,
        )

        logger.info("GPAgent.run — transcript length: %d chars", len(transcript))

        result = structured_output(
            context=context,
            target_model=GPAssessment,
            system_hint=SYSTEM_PROMPT,
            max_retries=self.max_retries,
            max_new_tokens=2048,
        )

        result["requires_review"] = True
        result["disclaimer"] = DISCLAIMER

        # Alert on emergency urgency
        urgency_level = ""
        if isinstance(result.get("urgency"), dict):
            urgency_level = result["urgency"].get("level", "")
        elif isinstance(result.get("urgency"), str):
            urgency_level = result["urgency"]

        if urgency_level.lower() == "emergency":
            logger.warning(
                "GP ASSESSMENT — EMERGENCY URGENCY: %s",
                result.get("chief_complaint", "see report"),
            )

        # Log inference
        try:
            log_inference(
                request_id="gp_agent",
                agents_invoked=["GPAgent"],
                model_versions={"medgemma": self.config.get("model_id", "medgemma-1.5-4b-it")},
                data_types=["transcript", "ehr"] if ehr_summary else ["transcript"],
                confidence_scores={},
            )
        except Exception:
            pass  # Audit failure must not block clinical output

        return result
