"""
Pathology clinical AI agent.

Interprets histopathology slides. Performs tissue type classification,
malignancy assessment, grading support.
Orchestrates: medical-cv-agent (patch extraction) → Path Foundation (embeddings)
→ MedGemma 4B (interpretation).

All outputs carry requires_review = True.
IHC interpretation not supported without specific fine-tuning.
Frozen sections not validated — FFPE only.

Owner agent definition: med_agents/pathologist-agent.md
Config: configs/agents/pathologist_agent.yaml
"""
from __future__ import annotations

from dataclasses import dataclass, field
from typing import Optional


DISCLAIMER = (
    "This pathology assessment was generated by AI and requires review by a "
    "qualified pathologist before any clinical action. This is not a validated "
    "diagnostic tool."
)


@dataclass
class PathologyReport:
    specimen_type: str
    tissue_assessment: str
    malignancy_indicator: str           # "benign" | "atypical" | "malignant" | "insufficient"
    grade: Optional[str]                # Tumour grade if applicable
    margin_status: Optional[str]        # "clear" | "involved" | "close" | "not assessed"
    additional_findings: list[str]
    requires_review: bool = True        # ALWAYS True — never modify
    confidence: float = 0.0
    disclaimer: str = field(default=DISCLAIMER)


class PathologistAgent:
    """
    Histopathology interpretation agent.
    Model stack: Path Foundation (embeddings) + MedGemma 4B (interpretation).

    Input quality dependency: adequate tissue sample required.
    Returns malignancy_indicator = "insufficient" if quality too low.
    """

    CONFIDENCE_THRESHOLD = 0.6

    def __init__(self, config: dict):
        self.config = config

    def run(self, wsi_path: str) -> PathologyReport:
        """
        Main entry point.
        wsi_path: path to de-identified whole slide image (.svs, .tif)
        Returns PathologyReport with requires_review=True always.
        """
        # TODO: implement full pipeline
        # 1. Extract tissue patches (medical-cv-agent)
        # 2. Embed patches (Path Foundation)
        # 3. Aggregate to slide-level embedding
        # 4. Interpret with MedGemma 4B
        # 5. Structure output
        raise NotImplementedError
