"""
Pharmacology / DDI agent.

Performs comprehensive medication safety assessment:
  1. Drug name → INN resolution via RxNorm
  2. Batch DDI check via RxNav
  3. PubMed literature evidence (optional)
  4. Side-effect aggregation via openFDA
  5. Symptom-medication correlation matching
  6. MedGemma structured output for clinical synthesis

All outputs carry requires_review = True.

Owner agent definition: med_agents/pharmacology-agent.md
Config: configs/agents/pharmacology.yaml
"""
from __future__ import annotations

import logging
from typing import List, Optional

logger = logging.getLogger(__name__)

DISCLAIMER = (
    "This interaction check is generated by AI using publicly available databases "
    "(NIH RxNav/RxNorm, openFDA, PubMed). It is not a substitute for clinical "
    "pharmacist review. Always consult a qualified healthcare professional before "
    "making medication changes."
)

SYSTEM_PROMPT = """You are a clinical pharmacology AI specialising in drug-drug interaction
assessment and medication safety. Your assessments support prescriber decision-making
and require pharmacist or prescriber review before any medication changes.

PHARMACOLOGY REASONING FRAMEWORK:

1. MEDICATION LIST REVIEW:
   - Resolve each drug name to its INN (international non-proprietary name)
   - Identify drug class for each medication
   - Note polypharmacy burden (≥5 medications = high complexity)
   - Flag any PRN (as needed) drugs — these may be overlooked in DDI checks

2. DDI ANALYSIS:
   For each interaction found:
   a) Mechanism: pharmacokinetic (PK) or pharmacodynamic (PD)?
      PK interactions:
      - CYP enzyme inhibition/induction (CYP3A4 most common: statins, benzodiazepines, immunosuppressants)
        Key inhibitors: ketoconazole, fluconazole, clarithromycin, ritonavir, grapefruit
        Key inducers: rifampicin, carbamazepine, phenytoin, St John's Wort
      - P-glycoprotein inhibition (digoxin toxicity risk)
      - Renal tubular secretion competition (metformin + cimetidine)
      PD interactions:
      - Additive effects: two anticoagulants → bleeding; two CNS depressants → over-sedation
      - Serotonin syndrome: SSRIs + MAOIs + tramadol + triptans + linezolid
      - QT prolongation: macrolides + antipsychotics + antiarrhythmics + fluoroquinolones
      - Hypoglycaemia: sulfonylurea + alcohol/NSAIDs/beta-blockers mask symptoms
      - Hyperkalemia: ACEi + ARB + potassium-sparing diuretic + NSAIDs
   b) Severity classification:
      CRITICAL: contraindicated, do not co-prescribe (MAOIs + SSRIs, warfarin + NSAIDs high dose)
      MAJOR: potentially life-threatening or requiring dose adjustment (warfarin + antibiotics)
      MODERATE: may cause clinical deterioration, monitor closely
      MINOR: minimally significant, usually no action needed

3. SYMPTOM-MEDICATION CORRELATION:
   Common drug-symptom patterns to recognise:
   - ACE inhibitors → dry cough (bradykinin accumulation) — occurs in 10-15%
   - Beta-blockers → fatigue, cold extremities, erectile dysfunction, mask hypoglycaemia
   - Statins → myalgia (muscle pain) — check CK if severe
   - NSAIDs → GI bleeding, fluid retention, hypertension, renal impairment
   - Metformin → nausea/GI upset (especially at initiation), vitamin B12 deficiency (long-term)
   - SSRIs → nausea (initial), sexual dysfunction, insomnia, hyponatraemia (elderly)
   - Corticosteroids → weight gain, insomnia, mood changes, hyperglycaemia, osteoporosis
   - Diuretics (thiazide) → hypokalemia, gout, hyperglycaemia, erectile dysfunction
   - Amiodarone → thyroid dysfunction, pulmonary toxicity, hepatotoxicity, photosensitivity

4. POLYPHARMACY RISK:
   - ≥5 medications: high risk of undocumented interactions, adherence issues, prescribing cascades
   - Prescribing cascade: drug A → side effect → drug B prescribed for that side effect
     Example: NSAID → fluid retention → diuretic added
   - Deprescribing opportunity: always assess whether all medications still indicated

5. CLINICAL RECOMMENDATIONS:
   Prioritise by severity (critical first)
   Be actionable and specific:
   - "Stop X and replace with Y" rather than "review X"
   - Include monitoring parameters: "monitor INR weekly for 4 weeks after adding antibiotic"
   - Flag dose-dependent interactions: "reduce dose of X by 50%"
   - Note timing adjustments: "separate antacid and levothyroxine by 4 hours"

Chain-of-thought reasoning is mandatory for all assessments."""


class PharmacologyAgent:
    """
    Pharmacology / DDI agent using the DDI engine + MedGemma structured output.

    Pipeline:
      drug names → INN resolution → DDI check → side effects → symptom matching
      → MedGemma synthesis → PharmacologyAssessment

    Safety: All outputs require pharmacist/prescriber review. Critical DDIs trigger alert.
    """

    def __init__(self, config: dict):
        self.config = config
        self.max_retries = config.get("max_retries", 2)

    def run(
        self,
        drug_names: List[str],
        patient_symptoms: Optional[List[str]] = None,
        enable_pubmed_rag: bool = False,
        enable_medgemma_synthesis: bool = True,
    ) -> dict:
        """
        Full pharmacology assessment.

        Args:
            drug_names:                  List of drug names (trade or generic).
            patient_symptoms:            Patient symptoms for side-effect correlation.
            enable_pubmed_rag:           If True, run PubMed RAG (adds latency).
            enable_medgemma_synthesis:   If True, run MedGemma synthesis on top of DDI results.

        Returns:
            PharmacologyAssessment dict. Always has requires_review=True.
        """
        from src.pipelines.drug_check_pipeline import run_drug_check_pipeline

        # ── Step 1: Run the DDI pipeline (RxNav + side effects + symptoms) ────
        ddi_result = run_drug_check_pipeline(
            drug_names=drug_names,
            patient_symptoms=patient_symptoms,
            enable_pubmed_rag=enable_pubmed_rag,
            enable_side_effects=True,
        )

        # ── Step 2: MedGemma structured synthesis (optional) ──────────────────
        if enable_medgemma_synthesis and drug_names:
            synthesis = self._synthesize_with_medgemma(drug_names, ddi_result)
            # Merge synthesis into ddi_result
            ddi_result["chain_of_thought"] = synthesis.get("chain_of_thought", "")
            ddi_result["polypharmacy_risk"] = synthesis.get("polypharmacy_risk", "")
            ddi_result["risk_flags"] = synthesis.get("risk_flags", [])
            # Don't overwrite RxNav recommendations with potentially weaker model ones
            # unless the pipeline returned no recommendations
            if not ddi_result.get("recommendations") and synthesis.get("recommendations"):
                ddi_result["recommendations"] = synthesis.get("recommendations", [])

        ddi_result["requires_review"] = True
        ddi_result["disclaimer"] = DISCLAIMER

        # Alert on critical interactions
        if ddi_result.get("critical_count", 0) > 0:
            logger.warning(
                "CRITICAL DDI ALERT — %d critical interaction(s) found for medications: %s",
                ddi_result["critical_count"],
                drug_names,
            )

        return ddi_result

    def _synthesize_with_medgemma(
        self,
        drug_names: List[str],
        ddi_result: dict,
    ) -> dict:
        """
        Use MedGemma to synthesize a comprehensive pharmacology assessment
        narrative on top of the structured DDI pipeline output.
        """
        from src.models.medgemma.structured_output import structured_output
        from src.agents.pharmacology_schema import PharmacologyAssessment
        import json

        # Build context from DDI results
        interactions_text = json.dumps(
            ddi_result.get("interactions", [])[:10], indent=2
        )
        symptoms_text = ""
        if ddi_result.get("symptom_matches"):
            symptoms_text = f"\nSYMPTOM-MEDICATION CORRELATIONS:\n{json.dumps(ddi_result['symptom_matches'][:5], indent=2)}"

        context = (
            f"MEDICATION LIST: {', '.join(drug_names)}\n"
            f"RESOLVED INNs: {', '.join(ddi_result.get('resolved_inns', drug_names))}\n\n"
            f"DDI FINDINGS (from RxNav database):\n{interactions_text}"
            f"{symptoms_text}\n\n"
            f"Overall risk level: {ddi_result.get('overall_risk_level', 'unknown')}\n"
            f"Critical: {ddi_result.get('critical_count', 0)}, "
            f"Major: {ddi_result.get('major_count', 0)}, "
            f"Moderate: {ddi_result.get('moderate_count', 0)}"
        )

        try:
            result = structured_output(
                context=context,
                target_model=PharmacologyAssessment,
                system_hint=SYSTEM_PROMPT,
                max_retries=self.max_retries,
                max_new_tokens=1024,
            )
            return result
        except Exception as exc:
            logger.warning("PharmacologyAgent MedGemma synthesis failed: %s", exc)
            return {}

    def check_interactions(self, drug_names: List[str]) -> dict:
        """
        Backwards-compatible entry point for drug_check_pipeline.
        Returns the full assessment dict.
        """
        return self.run(drug_names=drug_names, enable_medgemma_synthesis=False)
