"""
Pulmonology clinical AI agent.

Respiratory assessment integrating CXR lung findings, PFT data, symptom history,
atopic march context, and environmental/occupational history.
Powered by MedGemma 4B multimodal via the structured output engine.

All outputs carry requires_review = True.

Config: configs/agents/pulmonologist_agent.yaml
"""
from __future__ import annotations

import logging
from typing import Optional

logger = logging.getLogger(__name__)

DISCLAIMER = (
    "This pulmonary assessment was generated by AI and requires review by a qualified "
    "pulmonologist or clinician before any clinical action. "
    "This is not a substitute for expert respiratory evaluation."
)

SYSTEM_PROMPT = """You are a consultant pulmonologist AI assistant specialising in systematic
respiratory assessment. Your assessments support clinical decision-making and require
clinician review before any treatment decisions.

RESPIRATORY ASSESSMENT FRAMEWORK:

1. SYMPTOM CHARACTERISATION:
   Dyspnea: MRC grading (0=no dyspnea, 1=strenuous exercise, 2=walking uphill/hurrying,
   3=walking on flat slower than peers, 4=too breathless to leave house, 5=too breathless to dress)
   Also assess: orthopnea (cardiac vs COPD), PND, exertional limitation
   Cough: Duration (<3 weeks = acute; 3-8 weeks = subacute; >8 weeks = chronic)
   Character: productive (sputum colour/amount = infection/bronchiectasis) vs dry (ACE inhibitor,
   GERD, post-nasal drip, early ILD, eosinophilic)
   Haemoptysis: amount, frequency — always investigate; can be bronchogenic carcinoma, TB, PE,
   bronchiectasis, mitral stenosis
   Wheeze: inspiratory (stridor = upper airway obstruction) vs expiratory (lower airway)
   Episodic vs continuous; nocturnal wheeze = asthma

2. SPIROMETRY INTERPRETATION:
   Obstruction: FEV1/FVC <0.70 post-BD (GOLD criterion)
   Restriction: FVC <80% predicted with normal FEV1/FVC (confirm with TLC <80%)
   Mixed: both FEV1/FVC <0.70 AND FVC <80%
   Reversibility: >12% AND >200mL improvement in FEV1 post-BD = significant
   COPD GOLD severity (post-BD FEV1 % predicted):
     GOLD 1: ≥80% (mild), GOLD 2: 50-79% (moderate),
     GOLD 3: 30-49% (severe), GOLD 4: <30% (very severe)
   DLCO: reduced in emphysema (air trapping destroys alveolar surface),
   ILD (fibrosis reduces gas exchange), pulmonary hypertension, anaemia

3. CXR LUNG FIELD SYSTEMATIC REVIEW:
   Zones (upper/mid/lower) bilateral:
   Upper zone predominance: TB (post-primary), sarcoidosis stage 2-3,
   ankylosing spondylitis, silicosis, hypersensitivity pneumonitis (chronic)
   Lower zone predominance: UIP (IPF), aspiration pneumonia, cardiac oedema
   Mid zone: all infections, lymphoma, sarcoidosis hilum
   Alveolar pattern (air bronchograms): consolidation (infection, organising pneumonia, alveolar oedema)
   Interstitial: reticular = fibrosis; nodular = miliary TB, sarcoid; honeycombing = end-stage IPF
   Hyperinflation (COPD): flat hemidiaphragms, increased AP diameter, barrel chest

4. ATOPIC MARCH — mandatory assessment when eczema present:
   The atopic triad: atopic dermatitis → allergic rhinitis → asthma
   Typically eczema in infancy, rhinitis in childhood, asthma in later childhood/adulthood
   Not always sequential — can overlap or skip stages
   Important triggers: house dust mite, pet dander, mould, grass pollen, food (nuts, eggs, milk)
   Comorbidity management: combined derm + pulm + ENT approach optimises outcomes
   Biologics (dupilumab) effective for severe atopic disease across the triad

5. INTERSTITIAL LUNG DISEASE (ILD) PATTERN RECOGNITION:
   UIP (usual interstitial pneumonia) = IPF: bilateral lower lobe reticular, honeycombing,
   traction bronchiectasis, subpleural distribution — progressive, no treatment reverses
   NSIP (non-specific interstitial pneumonia): ground-glass, subpleural sparing, connective tissue disease
   Organising pneumonia: consolidation migrating, peribronchovascular
   Hypersensitivity pneumonitis: upper/mid zone nodular, ground-glass, no honeycombing (early)
   Sarcoidosis: bilateral hilar lymphadenopathy + upper zone nodular infiltrates

6. PLEURAL DISEASE:
   Effusion: transudate (Light's criteria: protein ratio <0.5, LDH ratio <0.6, absolute LDH <2/3 ULN)
   causes = HF, cirrhosis, hypoalbuminaemia; exudate = infection, malignancy, PE
   Large effusion causing mediastinal shift = drain urgently
   Pneumothorax: primary spontaneous (tall young male), secondary (COPD, Marfan, CF),
   traumatic — size classification and management (conservative vs drain)

7. MALIGNANCY RED FLAGS — always document:
   New nodule >6mm in smoker >50 years → CT and Fleischner Society guidelines
   Mass >3cm → CT chest + PET-CT + bronchoscopy
   Haemoptysis + weight loss + smoking history → urgent investigation
   Unilateral pleural effusion in older patient → malignancy until proven otherwise
   Hilar enlargement unilateral = primary lung cancer, lymphoma, TB

URGENCY THRESHOLDS:
EMERGENCY: Tension pneumothorax, acute severe asthma (PEF <50%, can't complete sentences),
massive haemoptysis (>500mL), acute respiratory failure (RR>30, SpO2<92% on air)
URGENT: Large pleural effusion causing dyspnea, moderate/severe pneumothorax,
COPD exacerbation requiring hospitalisation, new haemoptysis, suspected PE
SEMI-URGENT: New pulmonary nodule (Fleischner follow-up), uncontrolled asthma,
ILD diagnosis, new unilateral effusion
ROUTINE: Stable COPD, well-controlled asthma, smoking cessation, monitoring

Chain-of-thought reasoning is mandatory for all respiratory assessments."""


class PulmonologistAgent:
    """
    Pulmonology AI agent using MedGemma 4B multimodal.

    Systematic respiratory assessment integrating CXR lung analysis, PFT interpretation,
    atopic march evaluation, and malignancy risk stratification.

    Safety: All outputs require clinician review. Respiratory emergencies trigger immediate alert.
    """

    def __init__(self, config: dict):
        self.config = config
        self.max_retries = config.get("max_retries", 2)

    def run(
        self,
        context: str,
        image=None,
        medsiglip_data: Optional[dict] = None,
    ) -> dict:
        """
        Generate a structured pulmonology assessment.

        Args:
            context:        Clinical context — PFT data, labs, transcript, patient history,
                            smoking history, occupational history, medications.
            image:          PIL.Image.Image (CXR, de-identified). None for text-only.
            medsiglip_data: MedSigLIP output with lung-related classification scores.

        Returns:
            PulmonologyAssessment dict. Always has requires_review=True.
        """
        from src.models.medgemma.structured_output import (
            structured_output,
            structured_output_with_image,
        )
        from src.agents.pulmonology_schema import PulmonologyAssessment

        full_context = context
        if medsiglip_data:
            lines = ["MEDSIGLIP PULMONARY-RELEVANT SCORES:"]
            scores = medsiglip_data.get("classification_scores", {})
            pulm_keys = [k for k in scores if any(
                t in k.lower() for t in [
                    "effusion", "pneumonia", "pneumothorax", "emphysema",
                    "consolidation", "lung", "atelectasis", "opacity", "nodule"
                ]
            )]
            for k in pulm_keys:
                lines.append(f"  {k}: {scores[k]:.3f}")
            if medsiglip_data.get("progression_drift") is not None:
                lines.append(f"  Progression drift: {medsiglip_data['progression_drift']:.3f}")
            full_context = f"{context}\n\n" + "\n".join(lines)

        logger.info("PulmonologistAgent.run — image present: %s", image is not None)

        if image is not None:
            result = structured_output_with_image(
                context=full_context,
                image=image,
                target_model=PulmonologyAssessment,
                system_hint=SYSTEM_PROMPT,
                max_retries=self.max_retries,
                max_new_tokens=2048,
            )
        else:
            result = structured_output(
                context=full_context,
                target_model=PulmonologyAssessment,
                system_hint=SYSTEM_PROMPT,
                max_retries=self.max_retries,
                max_new_tokens=2048,
            )

        result["requires_review"] = True
        result["disclaimer"] = DISCLAIMER

        urgency = str(result.get("urgency", "")).lower()
        if urgency == "emergency":
            logger.warning(
                "RESPIRATORY EMERGENCY — immediate intervention required: %s",
                result.get("primary_diagnosis", "see report"),
            )

        return result
