"""
Radiology clinical AI agent.

Generates structured radiology reports from medical images (CXR, CT, MRI).
Uses MedGemma 4B multimodal via the structured output engine.
Integrates MedSigLIP progression scores when available.

All outputs carry requires_review = True and the standard disclaimer.
Emergency findings trigger immediate alert — never queue.

Owner agent definition: med_agents/radiologist-agent.md
Config: configs/agents/radiologist_agent.yaml
"""
from __future__ import annotations

import logging
from typing import Optional

logger = logging.getLogger(__name__)

DISCLAIMER = (
    "This radiology report was generated by AI and requires review by a qualified "
    "radiologist before any clinical action is taken. This is not a substitute for "
    "expert radiological interpretation."
)

# Findings that trigger immediate alert regardless of queue
CRITICAL_FINDINGS = [
    "tension pneumothorax",
    "massive pulmonary embolism",
    "aortic dissection",
    "large intracranial haemorrhage",
    "spinal cord compression",
]

SYSTEM_PROMPT = """You are a subspecialty-trained radiologist AI assistant specialising in
systematic image interpretation. Your reports are for clinical decision support only —
a qualified radiologist must review all findings before clinical action.

Your approach must be exhaustive and systematic:

FOR CHEST X-RAY (CXR) — use ABCs:
- Airway: trachea midline or deviated; carina angle (<70 deg normal)
- Breathing: lung fields bilateral — upper/mid/lower zones separately; compare both sides;
  consolidation, ground-glass, atelectasis, nodules, hyperinflation
- Cardiac: size (CTR <0.5 on PA = normal); shape; left/right heart borders; aortic knuckle
- Diaphragm: bilateral hemidiaphragm position; costophrenic angles (blunting = effusion);
  air under diaphragm (perforation)
- Everything else: bones (fractures, lytic lesions); soft tissues; lines/tubes position

FOR CT CHEST — systematic per-lobe:
- Airways: trachea, main bronchi, lobar bronchi (bronchiectasis, obstruction)
- Lung parenchyma: each lobe separately; ground-glass, consolidation, nodules (size, density,
  spiculation, cavitation), emphysema (centrilobular, panlobular), fibrosis (UIP vs NSIP pattern)
- Pleura: bilateral — effusion (simple, complex, loculated), pneumothorax, thickening
- Mediastinum: lymph nodes (short axis >10mm = enlarged); aorta (calibre, aneurysm);
  heart/pericardium; oesophagus
- Extrapulmonary: chest wall, upper abdomen if included

COMPARISON WITH PRIOR — always state explicitly:
1. What is new since prior study (most clinically important)
2. What has resolved or improved
3. What is unchanged but still significant
4. If no prior available — state this explicitly

CRITICAL FINDINGS — always alert for:
Tension pneumothorax, massive PE, aortic dissection, large pleural effusion causing shift,
cardiomegaly with pulmonary oedema, haemothorax, air bronchogram in consolidation

RULES:
- Never fabricate findings not in the image or clinical context
- Report normal structures explicitly — silence creates ambiguity
- Use standard radiology terminology (consolidation, not "shadow")
- Chain-of-thought reasoning is mandatory for every report"""


def run_radiology_report(
    context: str,
    image=None,
    medsiglip_data: Optional[dict] = None,
    max_retries: int = 2,
) -> dict:
    """
    Generate a structured radiology report.

    Args:
        context:        Clinical context string including patient history, indication,
                        prior studies, and any MedSigLIP results already computed.
        image:          PIL.Image.Image (de-identified). None for text-only review.
        medsiglip_data: Optional dict with MedSigLIP encoder output.
        max_retries:    Number of retry attempts on JSON failure.

    Returns:
        RadiologistReport dict with requires_review=True.
    """
    from src.models.medgemma.structured_output import (
        structured_output,
        structured_output_with_image,
    )
    from src.agents.radiology_schema import RadiologistReport

    full_context = context
    if medsiglip_data:
        full_context = f"{context}\n\n{_format_medsiglip_context(medsiglip_data)}"

    if image is not None:
        result = structured_output_with_image(
            context=full_context,
            image=image,
            target_model=RadiologistReport,
            system_hint=SYSTEM_PROMPT,
            max_retries=max_retries,
            max_new_tokens=2048,
        )
    else:
        result = structured_output(
            context=full_context,
            target_model=RadiologistReport,
            system_hint=SYSTEM_PROMPT,
            max_retries=max_retries,
            max_new_tokens=2048,
        )

    result["requires_review"] = True
    result["disclaimer"] = DISCLAIMER

    # Check for critical findings and log alert
    critical = _check_critical_findings_in_result(result)
    if critical:
        logger.warning(
            "CRITICAL RADIOLOGY FINDING — immediate notification required: %s", critical
        )
        result["critical_alert"] = critical

    return result


def _format_medsiglip_context(data: dict) -> str:
    """Format MedSigLIP results for inclusion in the clinical context."""
    lines = ["MEDSIGLIP QUANTITATIVE ANALYSIS (pre-computed before this report):"]

    if data.get("classification_scores"):
        lines.append("Zero-shot classification scores (top findings):")
        scores = data["classification_scores"]
        if isinstance(scores, dict):
            for finding, score in sorted(scores.items(), key=lambda x: -x[1])[:5]:
                lines.append(f"  {finding}: {score:.3f}")

    if data.get("progression_drift") is not None:
        drift = float(data["progression_drift"])
        if drift > 0.2:
            lines.append(f"Progression drift score: {drift:.3f} — elevated, suggests interval change")
        elif drift > 0.05:
            lines.append(f"Progression drift score: {drift:.3f} — moderate, possible change")
        else:
            lines.append(f"Progression drift score: {drift:.3f} — low, images appear similar to prior")

    if data.get("pairwise_similarity") is not None:
        sim = float(data["pairwise_similarity"])
        lines.append(f"Current vs prior embedding similarity: {sim:.3f}")

    if data.get("change_point_indices"):
        lines.append(f"Change-point regions identified at indices: {data['change_point_indices']}")

    lines.append(
        "Note: MedSigLIP scores are quantitative estimates to guide attention. "
        "Final findings must be based on direct image analysis."
    )
    return "\n".join(lines)


def _check_critical_findings_in_result(result: dict) -> list:
    """Scan report for critical findings requiring immediate alert."""
    critical_list = result.get("critical_findings", [])
    if critical_list:
        return critical_list

    # Also scan impression text as fallback
    impression = str(result.get("impression", "")).lower()
    found = []
    for pattern in CRITICAL_FINDINGS:
        if pattern in impression:
            found.append(pattern)
    return found


class RadiologistAgent:
    """
    Radiology AI agent using MedGemma 4B multimodal.

    Processes medical images + clinical context to produce structured RadiologistReports.
    Integrates with MedSigLIP encoder output when available.

    Safety: All outputs require radiologist review. Critical findings trigger alert.
    """

    def __init__(self, config: dict):
        self.config = config
        self.max_retries = config.get("max_retries", 2)

    def run(
        self,
        context: str,
        image=None,
        medsiglip_data: Optional[dict] = None,
    ) -> dict:
        """
        Generate a structured radiology report.

        Args:
            context:        Clinical context — transcript excerpt, patient history,
                            indication, prior imaging notes.
            image:          PIL.Image.Image (de-identified). None for text-only review.
            medsiglip_data: MedSigLIP encoder output dict.

        Returns:
            RadiologistReport dict. Always has requires_review=True.
        """
        logger.info("RadiologistAgent.run — image present: %s", image is not None)
        return run_radiology_report(
            context=context,
            image=image,
            medsiglip_data=medsiglip_data,
            max_retries=self.max_retries,
        )
