"""
Synthesis Agent — final multi-agent board synthesis.

Collects outputs from the GP agent and all consulted specialist agents,
synthesises them into a single structured visit record (VisitSynthesis),
and appends a chain-of-thought entry for the synthesis step itself.

All outputs carry requires_review = True — hardcoded, never configurable.
Owner agent definition: med_agents/medgemma-agent.md
"""
from __future__ import annotations

import json
import logging
from typing import Optional

logger = logging.getLogger(__name__)

DISCLAIMER = (
    "This synthesised clinical record was generated by AI using a multi-agent reasoning "
    "pipeline. It is intended for clinical decision support only. All findings require "
    "clinician review and professional judgement before any clinical action is taken."
)

SYSTEM_PROMPT = """You are a senior clinical decision-support AI synthesising findings from
a General Practitioner AI agent and multiple specialist AI agents.
Your role is to produce the final structured visit record that the doctor will review and edit.

SYNTHESIS INSTRUCTIONS:
1. Read the GP assessment (chief complaint, SOAP, ICD codes, urgency) as the primary framework
2. Integrate specialist findings — each specialist may confirm, refine, or add diagnoses
3. Consolidate recommended orders: remove duplicates, keep the most specific test
4. Produce a reason_for_visit that accurately reflects the primary presentation
5. Write a SOAP note that integrates all specialist findings into a coherent clinical narrative
6. Select the most important ICD-10 diagnoses (primary first, max 5)
7. List recommended orders with urgency and rationale (urgent orders first)
8. Write key_findings as 2-3 sentences: what was found, primary conclusion, most important action

RULES:
- Never fabricate findings not present in the agent inputs
- Chain-of-thought reasoning is mandatory — document your synthesis logic in cot_log
- Keep reason_for_visit concise (one sentence maximum)
- If specialist agents found emergency findings, reflect this in SOAP assessment/plan
- Do NOT include prescriptions — the doctor adds those after reviewing the AI output
- requires_review is ALWAYS True"""


class SynthesisAgent:
    """
    Final synthesis agent: collects all agent reports and produces a VisitSynthesis.

    Calls MedGemma via structured_output() with the VisitSynthesis schema.
    Appends a chain-of-thought entry for the synthesis step itself.
    """

    def __init__(self, config: dict):
        self.config = config
        self.max_retries = config.get("max_retries", 2)

    def run(
        self,
        transcript: str,
        ehr_summary: str,
        gp_assessment: dict,
        specialist_reports: dict[str, dict],
        config: Optional[dict] = None,
    ) -> dict:
        """
        Synthesise all agent outputs into a final VisitSynthesis.

        Args:
            transcript:         Clinical transcript.
            ehr_summary:        Formatted EHR context string.
            gp_assessment:      GPAssessment dict from GPAgent.
            specialist_reports: {agent_name: result_dict} from orchestrator.
            config:             Config override (unused, kept for API symmetry).

        Returns:
            VisitSynthesis dict with requires_review=True and cot_log populated.
        """
        from src.models.medgemma.structured_output import structured_output
        from src.agents.visit_synthesis_schema import VisitSynthesis

        context = self._build_synthesis_context(
            transcript, ehr_summary, gp_assessment, specialist_reports
        )

        logger.info(
            "SynthesisAgent.run — synthesising %d specialist report(s): %s",
            len(specialist_reports),
            list(specialist_reports.keys()),
        )

        result = structured_output(
            context=context,
            target_model=VisitSynthesis,
            system_hint=SYSTEM_PROMPT,
            max_retries=self.max_retries,
            max_new_tokens=3072,
        )

        result["requires_review"] = True
        result["disclaimer"] = DISCLAIMER

        # Append synthesis agent's own CoT entry to cot_log
        cot_log = result.get("cot_log", [])
        if not isinstance(cot_log, list):
            cot_log = []

        synthesis_cot = (
            f"SynthesisAgent combined inputs from: GPAgent"
            + (
                f", {', '.join(k.capitalize() + 'Agent' for k in specialist_reports.keys())}"
                if specialist_reports
                else ""
            )
            + f". Produced {len(result.get('diagnoses', []))} diagnoses and "
            + f"{len(result.get('recommended_orders', []))} orders."
        )
        cot_log.append({"agent": "SynthesisAgent", "reasoning": synthesis_cot})
        result["cot_log"] = cot_log

        # Populate agents_invoked if empty
        if not result.get("agents_invoked"):
            result["agents_invoked"] = (
                ["GPAgent"]
                + [f"{k.capitalize()}Agent" for k in specialist_reports.keys()]
                + ["SynthesisAgent"]
            )

        return result

    def _build_synthesis_context(
        self,
        transcript: str,
        ehr_summary: str,
        gp_assessment: dict,
        specialist_reports: dict[str, dict],
    ) -> str:
        """Build the full synthesis context string."""
        parts: list[str] = []

        parts.append(f"CLINICAL TRANSCRIPT:\n{transcript}")

        if ehr_summary:
            parts.append(f"PATIENT EHR SUMMARY:\n{ehr_summary}")

        # GP assessment — most important section
        gp_compact = {
            "chief_complaint": gp_assessment.get("chief_complaint", ""),
            "chain_of_thought": gp_assessment.get("chain_of_thought", ""),
            "soap": gp_assessment.get("soap", {}),
            "urgency": gp_assessment.get("urgency", {}),
            "differentials": gp_assessment.get("differentials", []),
            "recommended_workup": gp_assessment.get("recommended_workup", []),
            "icd_codes": gp_assessment.get("icd_codes", []),
            "summary": gp_assessment.get("summary", ""),
        }
        parts.append(f"GP ASSESSMENT:\n{json.dumps(gp_compact, indent=2)}")

        # Specialist reports
        for agent_name, report in specialist_reports.items():
            if report.get("_error"):
                parts.append(
                    f"{agent_name.upper()} AGENT: [Error — {report['_error']}]"
                )
                continue
            # Compact: exclude raw output and safety boilerplate fields
            compact = {
                k: v
                for k, v in report.items()
                if k not in ("_raw_output", "requires_review", "disclaimer")
                and not k.startswith("_")
            }
            parts.append(
                f"{agent_name.upper()} SPECIALIST REPORT:\n{json.dumps(compact, indent=2)}"
            )

        return "\n\n".join(parts)
